language: go

sudo: false

git:
  depth: false

go: 1.11.x

install:
  - go get -u github.com/gohugoio/hugo

script:
  - hugo

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: public
  on:
    branch: master
